name: dcgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - seaborn
  - pillow
  - jupyterlab
  - ipykernel
  - pip:
      - tqdm
